// <auto-generated />
using System;
using Fabric.Server.Desfire.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Desfire.Persistence.Migrations
{
    [DbContext(typeof(DesfireDbContext))]
    [Migration("20260707075751_ReplaceTransformationBlankType")]
    partial class ReplaceTransformationBlankType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("desfire")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.ChipDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SpecificationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_chip_designs_tenant_id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("chip_designs", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.DesfireDeviceLease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EncodingRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_device_leases_tenant_id");

                    b.HasIndex("AgentId", "DeviceId");

                    b.ToTable("device_leases", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.DesfireVariableSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_variable_sequences_tenant_id");

                    b.ToTable("variable_sequences", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.EncodingBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedRowsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalInputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TransformationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_encoding_batches_tenant_id");

                    b.HasIndex("TransformationId");

                    b.ToTable("encoding_batches", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.EncodingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardUid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CommandAuditJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("HardwareAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlanSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResolvedVariablesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TransformationId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariableConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CardUid");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_encoding_runs_tenant_id");

                    b.HasIndex("TransformationId");

                    b.HasIndex("RequestedAgentId", "RequestedDeviceId");

                    b.HasIndex("Status", "Priority", "RequestedAt");

                    b.ToTable("encoding_runs", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.KeyDiversificationStrategyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_key_diversification_strategies_tenant_id");

                    b.ToTable("key_diversification_strategies", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.KeyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiversificationStrategyId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_key_groups_tenant_id");

                    b.ToTable("key_groups", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.Transformation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AlwaysReadUid")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FromBlank")
                        .HasColumnType("boolean");

                    b.Property<string>("FromChipDesignName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequiredKeyGroupsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RequiredVariablesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToChipDesignName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariableConfigsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_transformations_tenant_id");

                    b.ToTable("transformations", "desfire");
                });

            modelBuilder.Entity("Fabric.Server.Desfire.Domain.KeyGroup", b =>
                {
                    b.OwnsMany("Fabric.Server.Desfire.Domain.KeyGroupKeySet", "KeySets", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("KeySetId")
                                .HasColumnType("integer");

                            b1.Property<Guid>("key_group_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("key_group_id", "KeySetId")
                                .IsUnique();

                            b1.ToTable("key_group_key_sets", "desfire");

                            b1.WithOwner()
                                .HasForeignKey("key_group_id");

                            b1.OwnsMany("Fabric.Server.Desfire.Domain.KeyGroupKey", "Keys", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("IsDiversified")
                                        .HasColumnType("boolean");

                                    b2.Property<int>("KeyId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("ProtectedValue")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("key_set_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("key_set_id", "KeyId")
                                        .IsUnique();

                                    b2.ToTable("key_group_keys", "desfire");

                                    b2.WithOwner()
                                        .HasForeignKey("key_set_id");
                                });

                            b1.Navigation("Keys");
                        });

                    b.Navigation("KeySets");
                });
#pragma warning restore 612, 618
        }
    }
}
