// <auto-generated />
using System;
using Fabric.Server.Identities.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Identities.Persistence.Migrations
{
    [DbContext(typeof(IdentitiesDbContext))]
    partial class IdentitiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identities")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Identities.Domain.ContractorAffiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contractor_affiliations");

                    b.HasIndex("IdentityId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_affiliations_tenant_id");

                    b.HasIndex("TenantId", "ContractorId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_affiliations_tenant_id_contractor_id");

                    b.HasIndex("TenantId", "IdentityId")
                        .HasDatabaseName("ix_contractor_affiliations_tenant_id_identity_id");

                    b.ToTable("contractor_affiliations", "identities");
                });

            modelBuilder.Entity("Fabric.Server.Identities.Domain.EmployeeAffiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_affiliations");

                    b.HasIndex("IdentityId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_affiliations_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_affiliations_tenant_id_employee_id");

                    b.HasIndex("TenantId", "IdentityId")
                        .HasDatabaseName("ix_employee_affiliations_tenant_id_identity_id");

                    b.ToTable("employee_affiliations", "identities");
                });

            modelBuilder.Entity("Fabric.Server.Identities.Domain.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(401)
                        .HasColumnType("character varying(401)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("preferred_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_identities");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_identities_tenant_id");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasDatabaseName("ix_identities_tenant_id_display_name");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_identities_tenant_id_email");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_identities_tenant_id_status");

                    b.ToTable("identities", "identities");
                });

            modelBuilder.Entity("Fabric.Server.Identities.Domain.VisitorAffiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("pk_visitor_affiliations");

                    b.HasIndex("IdentityId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_visitor_affiliations_tenant_id");

                    b.HasIndex("TenantId", "IdentityId")
                        .HasDatabaseName("ix_visitor_affiliations_tenant_id_identity_id");

                    b.HasIndex("TenantId", "VisitorId")
                        .IsUnique()
                        .HasDatabaseName("ix_visitor_affiliations_tenant_id_visitor_id");

                    b.ToTable("visitor_affiliations", "identities");
                });

            modelBuilder.Entity("Fabric.Server.Identities.Domain.ContractorAffiliation", b =>
                {
                    b.HasOne("Fabric.Server.Identities.Domain.Identity", null)
                        .WithMany("ContractorAffiliations")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Identities.Domain.EmployeeAffiliation", b =>
                {
                    b.HasOne("Fabric.Server.Identities.Domain.Identity", null)
                        .WithMany("EmployeeAffiliations")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Identities.Domain.VisitorAffiliation", b =>
                {
                    b.HasOne("Fabric.Server.Identities.Domain.Identity", null)
                        .WithMany("VisitorAffiliations")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Identities.Domain.Identity", b =>
                {
                    b.Navigation("ContractorAffiliations");

                    b.Navigation("EmployeeAffiliations");

                    b.Navigation("VisitorAffiliations");
                });
#pragma warning restore 612, 618
        }
    }
}
