using System.Text.Json.Serialization;
using Fabric.Server.AccessCatalog.Contracts;
using Fabric.Server.AccessCatalog.Domain;
using Fabric.Server.Core;
using Microsoft.AspNetCore.Mvc;

namespace Fabric.Server.AccessCatalog;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
[JsonSerializable(typeof(ApprovalDecisionKind))]
[JsonSerializable(typeof(ApprovalDecisionResponse))]
[JsonSerializable(typeof(ApprovalDecisionRole))]
[JsonSerializable(typeof(ApprovalDefinitionResponse))]
[JsonSerializable(typeof(ApprovalGroupMemberResponse))]
[JsonSerializable(typeof(ApprovalGroupResponse))]
[JsonSerializable(typeof(ApprovalGroupStatus))]
[JsonSerializable(typeof(ApprovalRequirementResponse))]
[JsonSerializable(typeof(ApprovalRequirementType))]
[JsonSerializable(typeof(ApprovalStatus))]
[JsonSerializable(typeof(AccessGrantResponse))]
[JsonSerializable(typeof(AccessDurationKind))]
[JsonSerializable(typeof(AccessGrantStatus))]
[JsonSerializable(typeof(AddPackageAccessItemRequest))]
[JsonSerializable(typeof(AssignmentChannel))]
[JsonSerializable(typeof(AssignmentSourceKind))]
[JsonSerializable(typeof(CatalogPackageResponse))]
[JsonSerializable(typeof(CatalogResponse))]
[JsonSerializable(typeof(CatalogStatus))]
[JsonSerializable(typeof(CreateApprovalDecisionRequest))]
[JsonSerializable(typeof(CreateApprovalDefinitionRequest))]
[JsonSerializable(typeof(CreateApprovalGroupMemberRequest))]
[JsonSerializable(typeof(CreateApprovalGroupRequest))]
[JsonSerializable(typeof(CreateAccessGrantRequest))]
[JsonSerializable(typeof(CreateCatalogRequest))]
[JsonSerializable(typeof(CreatePackageRequest))]
[JsonSerializable(typeof(CreatePackageRequestRequest))]
[JsonSerializable(typeof(LinkCatalogPackageRequest))]
[JsonSerializable(typeof(ListApprovalGroupsRequest))]
[JsonSerializable(typeof(ListApprovalRequirementsRequest))]
[JsonSerializable(typeof(PackageAccessItemResponse))]
[JsonSerializable(typeof(PackageRequestResponse))]
[JsonSerializable(typeof(PackageRequestStatus))]
[JsonSerializable(typeof(PackageResponse))]
[JsonSerializable(typeof(PackageStatus))]
[JsonSerializable(typeof(OrganizationalApprovalMode))]
[JsonSerializable(typeof(Page<AccessGrantResponse>))]
[JsonSerializable(typeof(Page<ApprovalDefinitionResponse>))]
[JsonSerializable(typeof(Page<ApprovalGroupMemberResponse>))]
[JsonSerializable(typeof(Page<ApprovalGroupResponse>))]
[JsonSerializable(typeof(Page<ApprovalRequirementResponse>))]
[JsonSerializable(typeof(Page<CatalogPackageResponse>))]
[JsonSerializable(typeof(Page<CatalogResponse>))]
[JsonSerializable(typeof(Page<PackageAccessItemResponse>))]
[JsonSerializable(typeof(Page<PackageRequestResponse>))]
[JsonSerializable(typeof(Page<PackageResponse>))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(UpdateApprovalDefinitionRequest))]
[JsonSerializable(typeof(UpdateApprovalGroupRequest))]
[JsonSerializable(typeof(UpdateCatalogRequest))]
[JsonSerializable(typeof(UpdatePackageRequest))]
internal sealed partial class AccessCatalogJsonSerializerContext : JsonSerializerContext;
