// <auto-generated />
using System;
using Fabric.Server.Kiosk.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Kiosk.Persistence.Migrations
{
    [DbContext(typeof(KioskDbContext))]
    [Migration("20260706041113_AddKioskDevices")]
    partial class AddKioskDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kiosk")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.Kiosk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ApiKeySalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("api_key_salt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowDefinitionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_kiosks_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosks_tenant_id_name");

                    b.HasIndex("TenantId", "ProfileId")
                        .HasDatabaseName("ix_kiosks_tenant_id_profile_id");

                    b.ToTable("kiosks", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltTextKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt_text_key");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("relative_path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_assets");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_assets_tenant_id");

                    b.HasIndex("TenantId", "ProfileId", "Name", "LanguageCode")
                        .HasDatabaseName("ix_kiosk_assets_tenant_profile_name_language");

                    b.ToTable("assets", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_id");

                    b.Property<bool>("CleanupOnSessionEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cleanup_on_session_end");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("KioskId")
                        .HasColumnType("uuid")
                        .HasColumnName("kiosk_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_devices");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_devices_tenant_id");

                    b.HasIndex("TenantId", "KioskId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_devices_tenant_kiosk_name");

                    b.HasIndex("TenantId", "KioskId", "Type")
                        .HasDatabaseName("ix_kiosk_devices_tenant_kiosk_type");

                    b.ToTable("devices", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskDeviceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_id");

                    b.Property<string>("BindingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("binding_key");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("KioskId")
                        .HasColumnType("uuid")
                        .HasColumnName("kiosk_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_device_assignments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_device_assignments_tenant_id");

                    b.HasIndex("TenantId", "KioskId", "BindingKey", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_device_assignments_tenant_kiosk_binding_priority");

                    b.ToTable("device_assignments", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskHardwareBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BindingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("binding_key");

                    b.Property<bool>("CleanupOnSessionEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cleanup_on_session_end");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("RequiredCapability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("required_capability");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_hardware_bindings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_hardware_bindings_tenant_id");

                    b.HasIndex("TenantId", "ProfileId", "BindingKey")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_hardware_bindings_tenant_profile_key");

                    b.ToTable("hardware_bindings", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_profiles");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_profiles_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_profiles_tenant_id_name");

                    b.ToTable("profiles", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskProfileLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_profile_languages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_profile_languages_tenant_id");

                    b.HasIndex("TenantId", "ProfileId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_profile_languages_tenant_id_profile_id_language_code");

                    b.ToTable("profile_languages", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CurrentInstructionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_instruction_id");

                    b.Property<string>("CurrentInstructionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("current_instruction_json");

                    b.Property<int>("CurrentInstructionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_instruction_version");

                    b.Property<Guid>("KioskId")
                        .HasColumnType("uuid")
                        .HasColumnName("kiosk_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<DateTimeOffset>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_interaction_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WorkflowInstanceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_sessions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sessions_tenant_id");

                    b.HasIndex("TenantId", "KioskId", "Status")
                        .HasDatabaseName("ix_kiosk_sessions_tenant_kiosk_status");

                    b.ToTable("sessions", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskThemeToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_theme_tokens");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_theme_tokens_tenant_id");

                    b.HasIndex("TenantId", "ProfileId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_theme_tokens_tenant_profile_key");

                    b.ToTable("theme_tokens", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("key");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_translations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_translations_tenant_id");

                    b.HasIndex("TenantId", "ProfileId", "LanguageCode", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_translations_tenant_profile_language_key");

                    b.ToTable("translations", "kiosk");
                });

            modelBuilder.Entity("Fabric.Server.Kiosk.Domain.KioskWelcomeSettings", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("BackgroundAssetName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("background_asset_name");

                    b.Property<string>("LogoAssetName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logo_asset_name");

                    b.Property<string>("StartButtonKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("start_button_key");

                    b.Property<string>("SubtitleKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subtitle_key");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title_key");

                    b.HasKey("ProfileId")
                        .HasName("pk_kiosk_welcome_settings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_welcome_settings_tenant_id");

                    b.ToTable("welcome_settings", "kiosk");
                });
#pragma warning restore 612, 618
        }
    }
}
