// <auto-generated />
using Fabric.Server.Tenants.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Tenants.Persistence.Migrations
{
    [DbContext(typeof(TenantsDbContext))]
    [Migration("20260619022656_TenantsInit")]
    partial class TenantsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenancy")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Tenants.Domain.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "tenancy", t =>
                        {
                            t.HasCheckConstraint("ck_tenants_logo_data_max_length", "logo_data IS NULL OR octet_length(logo_data) <= 1048576");
                        });
                });

            modelBuilder.Entity("Fabric.Server.Tenants.Domain.Tenant", b =>
                {
                    b.OwnsOne("Fabric.Server.Tenants.Domain.TenantConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("character varying(100)");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("Fabric.Server.Tenants.Domain.LogoSettings", "Logo", b2 =>
                                {
                                    b2.Property<string>("TenantConfigurationTenantId")
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("logo_content_type");

                                    b2.Property<byte[]>("Data")
                                        .IsRequired()
                                        .HasMaxLength(1048576)
                                        .HasColumnType("bytea")
                                        .HasColumnName("logo_data");

                                    b2.HasKey("TenantConfigurationTenantId");

                                    b2.ToTable("tenants", "tenancy");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantConfigurationTenantId");
                                });

                            b1.OwnsOne("Fabric.Server.Tenants.Domain.OidcSettings", "Oidc", b2 =>
                                {
                                    b2.Property<string>("TenantConfigurationTenantId")
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("ClientId")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("oidc_client_id");

                                    b2.Property<string>("MetadataUrl")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("oidc_metadata_url");

                                    b2.Property<bool>("RequireHttpsMetadata")
                                        .HasColumnType("boolean")
                                        .HasColumnName("oidc_require_https_metadata");

                                    b2.HasKey("TenantConfigurationTenantId");

                                    b2.ToTable("tenants", "tenancy");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantConfigurationTenantId");
                                });

                            b1.OwnsOne("Fabric.Server.Tenants.Domain.ThemeSettings", "Theme", b2 =>
                                {
                                    b2.Property<string>("TenantConfigurationTenantId")
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("ActiveBlueColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#deeeff")
                                        .HasColumnName("theme_active_blue_color");

                                    b2.Property<string>("BackgroundColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#f8f8f8")
                                        .HasColumnName("theme_background_color");

                                    b2.Property<string>("BorderColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#dddddd")
                                        .HasColumnName("theme_border_color");

                                    b2.Property<string>("ContentColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#ffffff")
                                        .HasColumnName("theme_content_color");

                                    b2.Property<string>("DangerColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#ff6467")
                                        .HasColumnName("theme_danger_color");

                                    b2.Property<string>("ErrorBackgroundColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#feeaea")
                                        .HasColumnName("theme_error_background_color");

                                    b2.Property<string>("ErrorColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#ff6467")
                                        .HasColumnName("theme_error_color");

                                    b2.Property<string>("HoverBlueColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#eef6ff")
                                        .HasColumnName("theme_hover_blue_color");

                                    b2.Property<string>("HoverGrayColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#f3f3f3")
                                        .HasColumnName("theme_hover_gray_color");

                                    b2.Property<string>("PrimaryColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#238cff")
                                        .HasColumnName("theme_primary_color");

                                    b2.Property<string>("SuccessBackgroundColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#e6faeb")
                                        .HasColumnName("theme_success_background_color");

                                    b2.Property<string>("SuccessColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#00c950")
                                        .HasColumnName("theme_success_color");

                                    b2.Property<string>("TextColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#212529")
                                        .HasColumnName("theme_text_color");

                                    b2.Property<string>("TextMutedColor")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasDefaultValue("#6c757d")
                                        .HasColumnName("theme_text_muted_color");

                                    b2.HasKey("TenantConfigurationTenantId");

                                    b2.ToTable("tenants", "tenancy");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantConfigurationTenantId");
                                });

                            b1.Navigation("Logo");

                            b1.Navigation("Oidc")
                                .IsRequired();

                            b1.Navigation("Theme")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
