// <auto-generated />
using Fabric.Server.Tenants.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Tenants.Persistence.Migrations
{
    [DbContext(typeof(TenantsDbContext))]
    [Migration("20260619014449_TenantsInit")]
    partial class TenantsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenancy")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Tenants.Domain.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "tenancy");
                });

            modelBuilder.Entity("Fabric.Server.Tenants.Domain.Tenant", b =>
                {
                    b.OwnsOne("Fabric.Server.Tenants.Domain.TenantConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("character varying(100)");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("Fabric.Server.Tenants.Domain.OidcSettings", "Oidc", b2 =>
                                {
                                    b2.Property<string>("TenantConfigurationTenantId")
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("ClientId")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("oidc_client_id");

                                    b2.Property<string>("MetadataUrl")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("oidc_metadata_url");

                                    b2.Property<bool>("RequireHttpsMetadata")
                                        .HasColumnType("boolean")
                                        .HasColumnName("oidc_require_https_metadata");

                                    b2.HasKey("TenantConfigurationTenantId");

                                    b2.ToTable("tenants", "tenancy");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantConfigurationTenantId");
                                });

                            b1.Navigation("Oidc")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
