// <auto-generated />
using System;
using Fabric.Server.AccessPolicies.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.AccessPolicies.Persistence.Migrations
{
    [DbContext(typeof(AccessPoliciesDbContext))]
    [Migration("20260622231008_AddAccessPolicySatisfiedBy")]
    partial class AddAccessPolicySatisfiedBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access_policies")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.AccessControlSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id")
                        .HasName("pk_access_control_systems");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_control_systems_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_access_control_systems_tenant_id_name");

                    b.ToTable("access_control_systems", "access_policies");

                    b.HasDiscriminator<string>("provider").HasValue("AccessControlSystem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.AccessLevelType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id")
                        .HasName("pk_access_level_types");

                    b.HasIndex("SystemId")
                        .HasDatabaseName("ix_access_level_types_system_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_level_types_tenant_id");

                    b.HasIndex("TenantId", "SystemId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_access_level_types_tenant_id_system_id_name");

                    b.ToTable("access_level_types", "access_policies");

                    b.HasDiscriminator<string>("provider").HasValue("AccessLevelType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.AccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<string>("ReconciliationFailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reconciliation_failure_reason");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reconciliation_status");

                    b.Property<Guid?>("SatisfiedByAccessLevelTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("satisfied_by_access_level_type_id");

                    b.Property<string>("SatisfiedByBadgeNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("satisfied_by_badge_number");

                    b.Property<Guid?>("SatisfiedByBadgeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("satisfied_by_badge_type_id");

                    b.Property<string>("SatisfiedByKind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("satisfied_by_kind");

                    b.Property<Guid?>("SatisfiedBySubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("satisfied_by_subject_id");

                    b.Property<Guid?>("SatisfiedBySystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("satisfied_by_system_id");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_access_policies");

                    b.HasIndex("EffectiveUntil")
                        .HasDatabaseName("ix_access_policies_effective_until");

                    b.HasIndex("ReconciliationStatus")
                        .HasDatabaseName("ix_access_policies_reconciliation_status");

                    b.HasIndex("SystemId")
                        .HasDatabaseName("ix_access_policies_system_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_policies_tenant_id");

                    b.ToTable("access_policies", "access_policies");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.BadgeType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id")
                        .HasName("pk_badge_types");

                    b.HasIndex("SystemId")
                        .HasDatabaseName("ix_badge_types_system_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_badge_types_tenant_id");

                    b.HasIndex("TenantId", "SystemId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_badge_types_tenant_id_system_id_name");

                    b.ToTable("badge_types", "access_policies");

                    b.HasDiscriminator<string>("provider").HasValue("BadgeType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.IdentityMapping", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_last_name");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("SubjectId", "SystemId")
                        .HasName("pk_identity_mappings");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_identity_mappings_external_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_identity_mappings_tenant_id");

                    b.ToTable("identity_mappings", "access_policies");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.IssuedProviderResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessLevelTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_level_type_id");

                    b.Property<int?>("BadgeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("badge_number");

                    b.Property<Guid?>("BadgeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_type_id");

                    b.Property<string>("ExternalPersonId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_person_id");

                    b.Property<string>("ExternalResourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_resource_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_kind");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_issued_provider_resources");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_issued_provider_resources_policy_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_issued_provider_resources_tenant_id");

                    b.HasIndex("SubjectId", "SystemId")
                        .HasDatabaseName("ix_issued_provider_resources_subject_id_system_id");

                    b.ToTable("issued_provider_resources", "access_policies");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.PolicyRequirement", b =>
                {
                    b.Property<Guid>("access_policy_id")
                        .HasColumnType("uuid")
                        .HasColumnName("access_policy_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("requirement_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requirement_type");

                    b.HasKey("access_policy_id")
                        .HasName("pk_policy_requirements");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_policy_requirements_tenant_id");

                    b.ToTable("policy_requirements", "access_policies");

                    b.HasDiscriminator<string>("requirement_type").HasValue("PolicyRequirement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UsedBadgeNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BadgeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("badge_number");

                    b.Property<Guid>("BadgeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_type_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_used_badge_numbers");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_used_badge_numbers_tenant_id");

                    b.HasIndex("TenantId", "SystemId", "BadgeTypeId", "BadgeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_used_badge_numbers_tenant_id_system_id_badge_type_id_badge_number");

                    b.ToTable("used_badge_numbers", "access_policies");
                });

            modelBuilder.Entity("lenel_access_level_type_badge_types", b =>
                {
                    b.Property<Guid>("access_level_type_id")
                        .HasColumnType("uuid")
                        .HasColumnName("access_level_type_id");

                    b.Property<Guid>("badge_type_id")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_type_id");

                    b.HasKey("access_level_type_id", "badge_type_id")
                        .HasName("pk_lenel_access_level_type_badge_types");

                    b.HasIndex("badge_type_id");

                    b.ToTable("lenel_access_level_type_badge_types", "access_policies");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.LenelAccessControlSystem", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.AccessControlSystem");

                    b.HasDiscriminator().HasValue("lenel");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UnipassAccessControlSystem", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.AccessControlSystem");

                    b.HasDiscriminator().HasValue("unipass");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.LenelAccessLevelType", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.AccessLevelType");

                    b.Property<Guid>("AccessLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_level_id");

                    b.HasIndex("TenantId", "SystemId", "AccessLevelId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_level_types_tenant_id_system_id_access_level_id");

                    b.HasDiscriminator().HasValue("lenel");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UnipassAccessLevelType", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.AccessLevelType");

                    b.Property<int>("AccessRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("access_rule_id");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.HasIndex("TenantId", "SystemId", "SiteId", "AccessRuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_level_types_tenant_id_system_id_site_id_access_rule_id");

                    b.HasDiscriminator().HasValue("unipass");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.LenelBadgeType", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.BadgeType");

                    b.Property<Guid>("BadgeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_type_id");

                    b.HasIndex("TenantId", "SystemId", "BadgeTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_badge_types_tenant_id_system_id_badge_type_id");

                    b.HasDiscriminator().HasValue("lenel");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UnipassBadgeType", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.BadgeType");

                    b.HasDiscriminator().HasValue("unipass");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.AccessRequirement", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.PolicyRequirement");

                    b.Property<Guid>("access_level_type_id")
                        .HasColumnType("uuid");

                    b.HasIndex("access_level_type_id");

                    b.HasDiscriminator().HasValue("access");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.CredentialRequirement", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessPolicies.Domain.PolicyRequirement");

                    b.Property<int?>("BadgeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("badge_number");

                    b.Property<Guid>("badge_type_id")
                        .HasColumnType("uuid");

                    b.HasIndex("badge_type_id");

                    b.HasDiscriminator().HasValue("credential");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.AccessPolicy", b =>
                {
                    b.OwnsOne("Fabric.Server.AccessPolicies.Domain.Subject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("AccessPolicyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subject_first_name");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("subject_id");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subject_last_name");

                            b1.Property<string>("SubjectType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("subject_type");

                            b1.HasKey("AccessPolicyId");

                            b1.ToTable("access_policies", "access_policies");

                            b1.WithOwner()
                                .HasForeignKey("AccessPolicyId");
                        });

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.PolicyRequirement", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.AccessPolicy", null)
                        .WithOne("Requirement")
                        .HasForeignKey("Fabric.Server.AccessPolicies.Domain.PolicyRequirement", "access_policy_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_policy_requirements_access_policies_access_policy_id");
                });

            modelBuilder.Entity("lenel_access_level_type_badge_types", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.LenelAccessLevelType", null)
                        .WithMany()
                        .HasForeignKey("access_level_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lenel_access_level_type_badge_types_access_level_types_access_level_type_id");

                    b.HasOne("Fabric.Server.AccessPolicies.Domain.LenelBadgeType", null)
                        .WithMany()
                        .HasForeignKey("badge_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lenel_access_level_type_badge_types_badge_types_badge_type_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.LenelAccessControlSystem", b =>
                {
                    b.OwnsOne("Fabric.Server.AccessPolicies.Domain.LenelSystemConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("LenelAccessControlSystemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApiKey")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("lenel_api_key");

                            b1.Property<string>("Endpoint")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("lenel_endpoint");

                            b1.Property<bool>("SslValidation")
                                .HasColumnType("boolean")
                                .HasColumnName("lenel_ssl_validation");

                            b1.HasKey("LenelAccessControlSystemId");

                            b1.ToTable("access_control_systems", "access_policies");

                            b1.WithOwner()
                                .HasForeignKey("LenelAccessControlSystemId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UnipassAccessControlSystem", b =>
                {
                    b.OwnsOne("Fabric.Server.AccessPolicies.Domain.UnipassSystemConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("UnipassAccessControlSystemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Endpoint")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("unipass_endpoint");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("unipass_password");

                            b1.Property<bool>("SslValidation")
                                .HasColumnType("boolean")
                                .HasColumnName("unipass_ssl_validation");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("unipass_username");

                            b1.HasKey("UnipassAccessControlSystemId");

                            b1.ToTable("access_control_systems", "access_policies");

                            b1.WithOwner()
                                .HasForeignKey("UnipassAccessControlSystemId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.LenelAccessLevelType", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.LenelAccessControlSystem", null)
                        .WithMany("AccessLevels")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_types_access_control_systems_system_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UnipassAccessLevelType", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.UnipassAccessControlSystem", null)
                        .WithMany("AccessLevels")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_types_access_control_systems_system_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.LenelBadgeType", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.LenelAccessControlSystem", null)
                        .WithMany("BadgeTypes")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_badge_types_access_control_systems_system_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UnipassBadgeType", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.UnipassAccessControlSystem", null)
                        .WithMany("BadgeTypes")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_badge_types_access_control_systems_system_id");

                    b.OwnsOne("Fabric.Server.AccessPolicies.Domain.BadgeRange", "Range", b1 =>
                        {
                            b1.Property<Guid>("UnipassBadgeTypeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Start")
                                .HasColumnType("integer")
                                .HasColumnName("range_start");

                            b1.Property<int>("Stop")
                                .HasColumnType("integer")
                                .HasColumnName("range_stop");

                            b1.HasKey("UnipassBadgeTypeId");

                            b1.ToTable("badge_types", "access_policies");

                            b1.WithOwner()
                                .HasForeignKey("UnipassBadgeTypeId");
                        });

                    b.Navigation("Range")
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.AccessRequirement", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.AccessLevelType", "AccessLevel")
                        .WithMany()
                        .HasForeignKey("access_level_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_requirements_access_level_types_access_level_type_id");

                    b.Navigation("AccessLevel");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.CredentialRequirement", b =>
                {
                    b.HasOne("Fabric.Server.AccessPolicies.Domain.BadgeType", "BadgeType")
                        .WithMany()
                        .HasForeignKey("badge_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_requirements_badge_types_badge_type_id");

                    b.Navigation("BadgeType");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.AccessPolicy", b =>
                {
                    b.Navigation("Requirement")
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.LenelAccessControlSystem", b =>
                {
                    b.Navigation("AccessLevels");

                    b.Navigation("BadgeTypes");
                });

            modelBuilder.Entity("Fabric.Server.AccessPolicies.Domain.UnipassAccessControlSystem", b =>
                {
                    b.Navigation("AccessLevels");

                    b.Navigation("BadgeTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
