// <auto-generated />
using System;
using Fabric.Server.Locations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Locations.Persistence.Migrations
{
    [DbContext(typeof(LocationsDbContext))]
    [Migration("20260619005254_LocationsInit")]
    partial class LocationsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("locations")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Locations.Domain.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("site_id")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_buildings_tenant_id");

                    b.HasIndex("site_id");

                    b.HasIndex("TenantId", "site_id", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_buildings_tenant_id_site_id_name");

                    b.ToTable("buildings", "locations");
                });

            modelBuilder.Entity("Fabric.Server.Locations.Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("WheelchairAccessible")
                        .HasColumnType("boolean")
                        .HasColumnName("wheelchair_accessible");

                    b.Property<Guid>("building_id")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_rooms_tenant_id");

                    b.HasIndex("building_id");

                    b.HasIndex("TenantId", "building_id", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_tenant_id_building_id_name");

                    b.ToTable("rooms", "locations");
                });

            modelBuilder.Entity("Fabric.Server.Locations.Domain.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sites_tenant_id");

                    b.ToTable("sites", "locations");
                });

            modelBuilder.Entity("Fabric.Server.Locations.Persistence.LocationLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_location_lookup");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_location_lookup_building_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_location_lookup_room_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_location_lookup_site_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_location_lookup_tenant_id");

                    b.ToTable("location_lookup", "locations");
                });

            modelBuilder.Entity("Fabric.Server.Locations.Domain.Building", b =>
                {
                    b.HasOne("Fabric.Server.Locations.Domain.Site", null)
                        .WithMany("Buildings")
                        .HasForeignKey("site_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_buildings_sites_site_id");
                });

            modelBuilder.Entity("Fabric.Server.Locations.Domain.Room", b =>
                {
                    b.HasOne("Fabric.Server.Locations.Domain.Building", null)
                        .WithMany("Rooms")
                        .HasForeignKey("building_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_buildings_building_id");
                });

            modelBuilder.Entity("Fabric.Server.Locations.Domain.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Fabric.Server.Locations.Domain.Site", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
