namespace Fabric.Server.Employees.Domain;

public enum EmployeeErrors
{
    EmployeeNotFound,
    EmployeeIdentityNotFound,
    EmployeeNameRequired,
    EmployeeAlreadyArchived,
    EmployeeNotArchived,
    EmployeeNumberAlreadyExists,
    DirectoryIdAlreadyExists,
    ManagerNotFound,
    ManagerCannotBeSelf,
    ContractDateRangeInvalid,
    EmployeePeriodDateRangeInvalid,
    EmployeeWorkLocationPrimaryRequired,
    EmployeeWorkLocationPrimaryConflict,
    OrganizationUnitNotFound,
    OrganizationUnitInactive,
    OrganizationUnitAlreadyExists,
    OrganizationUnitHasActiveChildren,
    OrganizationUnitHasActiveEmployees,
    OrganizationUnitParentCycle,
    PersonaNotFound,
    PersonaNameRequired,
    PersonaAlreadyExists,
    PersonaInactive,
    PersonaAssignedToEmployees,
    LeavePeriodNotFound,
    SuspensionPeriodNotFound,
    LocationNotFound,
    IdentityCreationFailed,
    IdentityUpdateFailed,
}
