// <auto-generated />
using System;
using Fabric.Server.Sagas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Sagas.Persistence.Migrations
{
    [DbContext(typeof(SagasDbContext))]
    [Migration("20260619005252_SagasInit")]
    partial class SagasInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sagas")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Sagas.VisitorPreOnboarding.VisitorPreOnboardingSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArrivalId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("qr_code");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visitor_pre_onboarding_sagas");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_next_retry_at");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_state");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_tenant_id");

                    b.HasIndex("VisitId", "InvitationId")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_visit_invitation");

                    b.ToTable("visitor_pre_onboarding_sagas", "sagas");
                });
#pragma warning restore 612, 618
        }
    }
}
