// <auto-generated />
using System;
using Fabric.Server.AccessCatalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.AccessCatalog.Persistence.Migrations
{
    [DbContext(typeof(AccessCatalogDbContext))]
    [Migration("20260722080308_AddAccessCatalogContext")]
    partial class AddAccessCatalogContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access_catalog")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentChannel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_channel");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_access_grants");

                    b.HasIndex("PackageId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_grants_tenant_id");

                    b.HasIndex("TenantId", "IdentityId", "Status")
                        .HasDatabaseName("ix_access_grants_tenant_id_identity_id_status");

                    b.ToTable("access_grants", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrantLocation", b =>
                {
                    b.Property<Guid>("AccessGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_grant_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("AccessGrantId", "LocationId")
                        .HasName("pk_access_grant_locations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_grant_locations_tenant_id");

                    b.HasIndex("TenantId", "AccessGrantId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_grant_locations_tenant_id_access_grant_id_location_id");

                    b.ToTable("access_grant_locations", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_catalogs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalogs_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_catalogs_tenant_id_name");

                    b.ToTable("catalogs", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.CatalogPackage", b =>
                {
                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<bool>("IsRequestable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_requestable");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("CatalogId", "PackageId")
                        .HasName("pk_catalog_packages");

                    b.HasIndex("PackageId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_packages_tenant_id");

                    b.HasIndex("TenantId", "CatalogId", "PackageId")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_packages_tenant_id_catalog_id_package_id");

                    b.ToTable("catalog_packages", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_packages_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_packages_tenant_id_name");

                    b.ToTable("packages", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageAccessItem", b =>
                {
                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("PackageId", "AccessItemId")
                        .HasName("pk_package_access_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_package_access_items_tenant_id");

                    b.HasIndex("TenantId", "PackageId", "AccessItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_package_access_items_tenant_id_package_id_access_item_id");

                    b.ToTable("package_access_items", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrant", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_grants_packages_package_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrantLocation", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.AccessGrant", null)
                        .WithMany()
                        .HasForeignKey("AccessGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_grant_locations_access_grants_access_grant_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.CatalogPackage", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Catalog", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_packages_catalogs_catalog_id");

                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_packages_packages_package_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageAccessItem", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_access_items_packages_package_id");
                });
#pragma warning restore 612, 618
        }
    }
}
