// <auto-generated />
using System;
using Fabric.Server.AccessCatalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.AccessCatalog.Persistence.Migrations
{
    [DbContext(typeof(AccessCatalogDbContext))]
    partial class AccessCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access_catalog")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentChannel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_channel");

                    b.Property<string>("DurationKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration_kind");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_access_grants");

                    b.HasIndex("PackageId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_grants_tenant_id");

                    b.HasIndex("TenantId", "IdentityId", "Status")
                        .HasDatabaseName("ix_access_grants_tenant_id_identity_id_status");

                    b.ToTable("access_grants", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrantLocation", b =>
                {
                    b.Property<Guid>("AccessGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_grant_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("AccessGrantId", "LocationId")
                        .HasName("pk_access_grant_locations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_grant_locations_tenant_id");

                    b.HasIndex("TenantId", "AccessGrantId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_grant_locations_tenant_id_access_grant_id_location_id");

                    b.ToTable("access_grant_locations", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApprovalRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_requirement_id");

                    b.Property<Guid>("ApproverIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_identity_id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision_kind");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_approval_decisions");

                    b.HasIndex("ApprovalRequirementId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_approval_decisions_tenant_id");

                    b.HasIndex("TenantId", "ApprovalRequirementId")
                        .HasDatabaseName("ix_approval_decisions_tenant_id_approval_requirement_id");

                    b.HasIndex("TenantId", "RequestId")
                        .HasDatabaseName("ix_approval_decisions_tenant_id_request_id");

                    b.ToTable("approval_decisions", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<Guid?>("DestinationApprovalGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_approval_group_id");

                    b.Property<int>("OrganizationalApprovalLevels")
                        .HasColumnType("integer")
                        .HasColumnName("organizational_approval_levels");

                    b.Property<string>("OrganizationalApprovalMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organizational_approval_mode");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_approval_definitions");

                    b.HasIndex("DestinationApprovalGroupId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_approval_definitions_tenant_id");

                    b.HasIndex("TenantId", "AccessItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_approval_definitions_tenant_id_access_item_id");

                    b.ToTable("approval_definitions", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_approval_groups");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_approval_groups_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_approval_groups_tenant_id_name");

                    b.ToTable("approval_groups", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApprovalGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_group_id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid>("ResponsibleLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_approval_group_members");

                    b.HasIndex("ApprovalGroupId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_approval_group_members_tenant_id");

                    b.HasIndex("TenantId", "ApprovalGroupId", "IdentityId", "ResponsibleLocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_approval_group_members_tenant_id_group_identity_location");

                    b.ToTable("approval_group_members", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<Guid?>("ApprovalGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_group_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("RequiredApproverIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_approver_identity_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SystemApprovalReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("system_approval_reason");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_approval_requirements");

                    b.HasIndex("ApprovalGroupId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_approval_requirements_tenant_id");

                    b.HasIndex("TenantId", "RequestId", "Status")
                        .HasDatabaseName("ix_approval_requirements_tenant_id_request_id_status");

                    b.HasIndex("TenantId", "RequiredApproverIdentityId", "Status")
                        .HasDatabaseName("ix_approval_requirements_tenant_id_required_approver_identity_id_status");

                    b.ToTable("approval_requirements", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_catalogs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalogs_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_catalogs_tenant_id_name");

                    b.ToTable("catalogs", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.CatalogPackage", b =>
                {
                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<bool>("IsRequestable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_requestable");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("CatalogId", "PackageId")
                        .HasName("pk_catalog_packages");

                    b.HasIndex("PackageId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_packages_tenant_id");

                    b.HasIndex("TenantId", "CatalogId", "PackageId")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_packages_tenant_id_catalog_id_package_id");

                    b.ToTable("catalog_packages", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_packages_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_packages_tenant_id_name");

                    b.ToTable("packages", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageAccessItem", b =>
                {
                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("PackageId", "AccessItemId")
                        .HasName("pk_package_access_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_package_access_items_tenant_id");

                    b.HasIndex("TenantId", "PackageId", "AccessItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_package_access_items_tenant_id_package_id_access_item_id");

                    b.ToTable("package_access_items", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiaryIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_identity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DurationKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration_kind");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("RequestReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("request_reason");

                    b.Property<Guid>("RequesterIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_identity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_package_requests");

                    b.HasIndex("PackageId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_package_requests_tenant_id");

                    b.HasIndex("TenantId", "BeneficiaryIdentityId", "Status")
                        .HasDatabaseName("ix_package_requests_tenant_id_beneficiary_identity_id_status");

                    b.HasIndex("TenantId", "PackageId", "Status")
                        .HasDatabaseName("ix_package_requests_tenant_id_package_id_status");

                    b.HasIndex("TenantId", "RequesterIdentityId", "Status")
                        .HasDatabaseName("ix_package_requests_tenant_id_requester_identity_id_status");

                    b.ToTable("package_requests", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageRequestLocation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("RequestId", "LocationId")
                        .HasName("pk_package_request_locations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_package_request_locations_tenant_id");

                    b.HasIndex("TenantId", "RequestId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_package_request_locations_tenant_id_request_id_location_id");

                    b.ToTable("package_request_locations", "access_catalog");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrant", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_grants_packages_package_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.AccessGrantLocation", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.AccessGrant", null)
                        .WithMany()
                        .HasForeignKey("AccessGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_grant_locations_access_grants_access_grant_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalDecision", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.ApprovalRequirement", null)
                        .WithMany()
                        .HasForeignKey("ApprovalRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_decisions_approval_requirements_approval_requirement_id");

                    b.HasOne("Fabric.Server.AccessCatalog.Domain.PackageRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_decisions_package_requests_request_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalDefinition", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.ApprovalGroup", null)
                        .WithMany()
                        .HasForeignKey("DestinationApprovalGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_approval_definitions_approval_groups_destination_approval_group_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalGroupMember", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.ApprovalGroup", null)
                        .WithMany()
                        .HasForeignKey("ApprovalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_group_members_approval_groups_approval_group_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.ApprovalRequirement", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.ApprovalGroup", null)
                        .WithMany()
                        .HasForeignKey("ApprovalGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_approval_requirements_approval_groups_approval_group_id");

                    b.HasOne("Fabric.Server.AccessCatalog.Domain.PackageRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_requirements_package_requests_request_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.CatalogPackage", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Catalog", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_packages_catalogs_catalog_id");

                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_packages_packages_package_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageAccessItem", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_access_items_packages_package_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageRequest", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_requests_packages_package_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessCatalog.Domain.PackageRequestLocation", b =>
                {
                    b.HasOne("Fabric.Server.AccessCatalog.Domain.PackageRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_request_locations_package_requests_request_id");
                });
#pragma warning restore 612, 618
        }
    }
}
