// <auto-generated />
using System;
using Fabric.Server.CredentialManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.CredentialManagement.Persistence.Migrations
{
    [DbContext(typeof(CredentialManagementDbContext))]
    partial class CredentialManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("credential_management")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CredentialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("credential_number");

                    b.Property<Guid>("CredentialTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_type_id");

                    b.Property<string>("DurationKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration_kind");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_text");

                    b.Property<Guid?>("RequestedByIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_identity_id");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("CredentialTypeId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credentials_tenant_id");

                    b.HasIndex("TenantId", "IdentityId")
                        .HasDatabaseName("ix_credentials_tenant_id_identity_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_credentials_tenant_id_status");

                    b.HasIndex("TenantId", "CredentialTypeId", "CredentialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_tenant_id_type_number");

                    b.HasIndex("TenantId", "SourceKind", "SourceId")
                        .HasDatabaseName("ix_credentials_tenant_id_source");

                    b.ToTable("credentials", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialProvisioningTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<Guid>("CredentialTypeTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_type_target_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provisioned_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credential_provisioning_transactions");

                    b.HasIndex("CredentialId");

                    b.HasIndex("CredentialTypeTargetId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_provisioning_transactions_tenant_id");

                    b.HasIndex("TenantId", "CredentialId")
                        .HasDatabaseName("ix_credential_provisioning_transactions_tenant_id_credential_id");

                    b.HasIndex("TenantId", "ScheduledFor")
                        .HasDatabaseName("ix_credential_provisioning_transactions_tenant_id_scheduled_for");

                    b.HasIndex("TenantId", "AccessControlSystemId", "Status")
                        .HasDatabaseName("ix_credential_provisioning_transactions_tenant_id_system_status");

                    b.ToTable("credential_provisioning_transactions", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CredentialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("credential_number");

                    b.Property<Guid>("CredentialTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_type_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_text");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid?>("RequestedByIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_identity_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credential_reservations");

                    b.HasIndex("CredentialTypeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_reservations_tenant_id");

                    b.HasIndex("TenantId", "IdentityId")
                        .HasDatabaseName("ix_credential_reservations_tenant_id_identity_id");

                    b.HasIndex("TenantId", "CredentialTypeId", "CredentialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_reservations_tenant_id_active_number")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("TenantId", "SourceKind", "SourceId")
                        .HasDatabaseName("ix_credential_reservations_tenant_id_source");

                    b.ToTable("credential_reservations", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("NearLimitThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("near_limit_threshold");

                    b.Property<int>("RangeStart")
                        .HasColumnType("integer")
                        .HasColumnName("range_start");

                    b.Property<int>("RangeStop")
                        .HasColumnType("integer")
                        .HasColumnName("range_stop");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("technology");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credential_types");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_types_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_types_tenant_id_name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_credential_types_tenant_id_status");

                    b.HasIndex("TenantId", "Technology")
                        .HasDatabaseName("ix_credential_types_tenant_id_technology");

                    b.ToTable("credential_types", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialTypeTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_type_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid?>("ProviderCredentialTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_credential_type_id");

                    b.Property<string>("ProvisioningTiming")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provisioning_timing");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credential_type_targets");

                    b.HasIndex("CredentialTypeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_type_targets_tenant_id");

                    b.HasIndex("TenantId", "AccessControlSystemId")
                        .HasDatabaseName("ix_credential_type_targets_tenant_id_system");

                    b.HasIndex("TenantId", "CredentialTypeId", "AccessControlSystemId")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_type_targets_tenant_id_type_system");

                    b.ToTable("credential_type_targets", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.Credential", b =>
                {
                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialType", null)
                        .WithMany()
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialProvisioningTransaction", b =>
                {
                    b.HasOne("Fabric.Server.CredentialManagement.Domain.Credential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialTypeTarget", null)
                        .WithMany()
                        .HasForeignKey("CredentialTypeTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialReservation", b =>
                {
                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialType", null)
                        .WithMany()
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialTypeTarget", b =>
                {
                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialType", null)
                        .WithMany("Targets")
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialType", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
