using System.Text.Json.Serialization;
using Fabric.Server.AccessControl.Contracts;
using Fabric.Server.AccessControl.Domain;
using Fabric.Server.Core;
using Microsoft.AspNetCore.Mvc;

namespace Fabric.Server.AccessControl;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
[JsonSerializable(typeof(AccessControlProviderKind))]
[JsonSerializable(typeof(ProvisioningTiming))]
[JsonSerializable(typeof(AccessControlSystemLocationResponse))]
[JsonSerializable(typeof(AccessControlSystemResponse))]
[JsonSerializable(typeof(AccessControlSystemStatus))]
[JsonSerializable(typeof(AccessItemResponse))]
[JsonSerializable(typeof(AccessItemStatus))]
[JsonSerializable(typeof(AccessLevelTargetResponse))]
[JsonSerializable(typeof(CreatePACSAssignmentsRequest))]
[JsonSerializable(typeof(ListPACSSubjectProvisioningsRequest))]
[JsonSerializable(typeof(CreateAccessItemRequest))]
[JsonSerializable(typeof(CreateUnipassAccessControlSystemRequest))]
[JsonSerializable(typeof(CreateUnipassAccessLevelTargetRequest))]
[JsonSerializable(typeof(LinkAccessControlSystemLocationRequest))]
[JsonSerializable(typeof(PACSAssignmentResponse))]
[JsonSerializable(typeof(PACSAssignmentResponse[]))]
[JsonSerializable(typeof(PACSAssignmentDurationKind))]
[JsonSerializable(typeof(PACSAssignmentStatus))]
[JsonSerializable(typeof(PACSProvisioningResponse))]
[JsonSerializable(typeof(PACSProvisioningStatus))]
[JsonSerializable(typeof(PACSSubjectProvisioningReason))]
[JsonSerializable(typeof(PACSSubjectProvisioningResponse))]
[JsonSerializable(typeof(PACSSubjectProvisioningResultResponse))]
[JsonSerializable(typeof(PACSSubjectProvisioningSourceKind))]
[JsonSerializable(typeof(PACSSubjectProvisioningStatus))]
[JsonSerializable(typeof(PACSSubjectResponse))]
[JsonSerializable(typeof(PACSSubjectState))]
[JsonSerializable(typeof(Page<AccessControlSystemLocationResponse>))]
[JsonSerializable(typeof(Page<AccessControlSystemResponse>))]
[JsonSerializable(typeof(Page<AccessItemResponse>))]
[JsonSerializable(typeof(Page<AccessLevelTargetResponse>))]
[JsonSerializable(typeof(Page<PACSAssignmentResponse>))]
[JsonSerializable(typeof(Page<PACSProvisioningResponse>))]
[JsonSerializable(typeof(Page<PACSSubjectProvisioningResponse>))]
[JsonSerializable(typeof(Page<PACSSubjectResponse>))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(ResolveAccessControlSystemResponse))]
[JsonSerializable(typeof(SystemMetadata))]
[JsonSerializable(typeof(UnipassAccessLevelTargetResponse))]
[JsonSerializable(typeof(UnipassMetadata))]
[JsonSerializable(typeof(UpsertPACSSubjectProvisioningRequest))]
[JsonSerializable(typeof(UpdateAccessItemRequest))]
[JsonSerializable(typeof(UpdateUnipassAccessControlSystemRequest))]
[JsonSerializable(typeof(UpdateUnipassAccessLevelTargetRequest))]
internal sealed partial class AccessControlJsonSerializerContext : JsonSerializerContext;
