// <auto-generated />
using System;
using Fabric.Server.Reception.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Reception.Persistence.Migrations
{
    [DbContext(typeof(ReceptionDbContext))]
    [Migration("20260714091826_RelaxArrivalCodeUniqueness")]
    partial class RelaxArrivalCodeUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reception")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ArrivalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("expected_arrival_id")
                        .HasColumnType("uuid")
                        .HasColumnName("expected_arrival_id");

                    b.HasKey("Id")
                        .HasName("pk_arrival_entries");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_arrival_entries_tenant_id");

                    b.HasIndex("expected_arrival_id")
                        .HasDatabaseName("ix_arrival_entries_expected_arrival_id");

                    b.ToTable("arrival_entries", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.CheckInDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("expected_arrival_id")
                        .HasColumnType("uuid")
                        .HasColumnName("expected_arrival_id");

                    b.HasKey("Id")
                        .HasName("pk_check_in_documents");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_check_in_documents_tenant_id");

                    b.HasIndex("expected_arrival_id")
                        .HasDatabaseName("ix_check_in_documents_expected_arrival_id");

                    b.ToTable("check_in_documents", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ExpectedArrival", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arrival_code");

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("checked_in");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<Guid?>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("ExpectedArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_arrival_time");

                    b.Property<DateTimeOffset>("ExpectedOffboardTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_offboard_time");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<Guid?>("JobAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_assignment_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset?>("OffboardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offboarded_at");

                    b.Property<DateTimeOffset?>("OnboardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("pk_expected_arrivals");

                    b.HasIndex("ContractorId")
                        .HasDatabaseName("ix_expected_arrivals_contractor_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_expected_arrivals_location_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_expected_arrivals_tenant_id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_expected_arrivals_visitor_id");

                    b.HasIndex("TenantId", "ArrivalCode")
                        .HasDatabaseName("ix_expected_arrivals_tenant_id_arrival_code");

                    b.ToTable("expected_arrivals", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ReceptionAccessRuleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessLevelTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_level_type_id");

                    b.Property<int>("GracePeriodMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("grace_period_minutes");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_access_rule_assignments");

                    b.HasIndex("AccessLevelTypeId")
                        .HasDatabaseName("ix_access_rule_assignments_access_level_type_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_access_rule_assignments_location_id");

                    b.HasIndex("SystemId")
                        .HasDatabaseName("ix_access_rule_assignments_system_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_rule_assignments_tenant_id");

                    b.HasIndex("Trigger")
                        .HasDatabaseName("ix_access_rule_assignments_trigger");

                    b.ToTable("access_rule_assignments", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ReceptionAssignedAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessLevelTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_level_type_id");

                    b.Property<Guid>("AccessPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_policy_id");

                    b.Property<Guid>("ArrivalId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_id");

                    b.Property<Guid>("RuleAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_assignment_id");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_assigned_access_policies");

                    b.HasIndex("AccessPolicyId")
                        .HasDatabaseName("ix_assigned_access_policies_access_policy_id");

                    b.HasIndex("ArrivalId")
                        .HasDatabaseName("ix_assigned_access_policies_arrival_id");

                    b.HasIndex("RuleAssignmentId")
                        .HasDatabaseName("ix_assigned_access_policies_rule_assignment_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_assigned_access_policies_tenant_id");

                    b.HasIndex("ArrivalId", "RuleAssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_assigned_access_policies_arrival_id_rule_assignment_id");

                    b.ToTable("assigned_access_policies", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ReceptionKiosk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ApiKeySalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("api_key_salt");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("IdentityVerificationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identity_verification_method");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OnboardingGracePeriodMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("onboarding_grace_period_minutes");

                    b.Property<bool>("RequireFacePicture")
                        .HasColumnType("boolean")
                        .HasColumnName("require_face_picture");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_reception_kiosks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_reception_kiosks_tenant_id");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_reception_kiosks_tenant_id_location_id");

                    b.ToTable("reception_kiosks", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ArrivalEntry", b =>
                {
                    b.HasOne("Fabric.Server.Reception.Domain.ExpectedArrival", null)
                        .WithMany("Entries")
                        .HasForeignKey("expected_arrival_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arrival_entries_expected_arrivals_expected_arrival_id");

                    b.OwnsOne("Fabric.Server.Reception.Domain.ReceptionActor", "Actor", b1 =>
                        {
                            b1.Property<Guid>("ArrivalEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("actor_display_name");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("actor_identifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("actor_type");

                            b1.HasKey("ArrivalEntryId");

                            b1.ToTable("arrival_entries", "reception");

                            b1.WithOwner()
                                .HasForeignKey("ArrivalEntryId");
                        });

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.CheckInDocument", b =>
                {
                    b.HasOne("Fabric.Server.Reception.Domain.ExpectedArrival", null)
                        .WithMany("Documents")
                        .HasForeignKey("expected_arrival_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_in_documents_expected_arrivals_expected_arrival_id");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ExpectedArrival", b =>
                {
                    b.OwnsOne("Fabric.Server.Reception.Domain.ReceptionActor", "OffboardedBy", b1 =>
                        {
                            b1.Property<Guid>("ExpectedArrivalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("offboarded_by_display_name");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("offboarded_by_identifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("offboarded_by_type");

                            b1.HasKey("ExpectedArrivalId");

                            b1.ToTable("expected_arrivals", "reception");

                            b1.WithOwner()
                                .HasForeignKey("ExpectedArrivalId");
                        });

                    b.OwnsOne("Fabric.Server.Reception.Domain.ReceptionActor", "OnboardedBy", b1 =>
                        {
                            b1.Property<Guid>("ExpectedArrivalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("onboarded_by_display_name");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("onboarded_by_identifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("onboarded_by_type");

                            b1.HasKey("ExpectedArrivalId");

                            b1.ToTable("expected_arrivals", "reception");

                            b1.WithOwner()
                                .HasForeignKey("ExpectedArrivalId");
                        });

                    b.Navigation("OffboardedBy");

                    b.Navigation("OnboardedBy");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ExpectedArrival", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
