// <auto-generated />
using System;
using Fabric.Server.Reception.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Reception.Persistence.Migrations
{
    [DbContext(typeof(ReceptionDbContext))]
    [Migration("20260619005256_ReceptionInit")]
    partial class ReceptionInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reception")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ArrivalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("expected_arrival_id")
                        .HasColumnType("uuid")
                        .HasColumnName("expected_arrival_id");

                    b.HasKey("Id")
                        .HasName("pk_arrival_entries");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_arrival_entries_tenant_id");

                    b.HasIndex("expected_arrival_id")
                        .HasDatabaseName("ix_arrival_entries_expected_arrival_id");

                    b.ToTable("arrival_entries", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.CheckInDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("expected_arrival_id")
                        .HasColumnType("uuid")
                        .HasColumnName("expected_arrival_id");

                    b.HasKey("Id")
                        .HasName("pk_check_in_documents");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_check_in_documents_tenant_id");

                    b.HasIndex("expected_arrival_id")
                        .HasDatabaseName("ix_check_in_documents_expected_arrival_id");

                    b.ToTable("check_in_documents", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ExpectedArrival", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arrival_code");

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("checked_in");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<Guid?>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("ExpectedArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_arrival_time");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<Guid?>("JobAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_assignment_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset?>("OffboardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offboarded_at");

                    b.Property<DateTimeOffset?>("OnboardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("pk_expected_arrivals");

                    b.HasIndex("ContractorId")
                        .HasDatabaseName("ix_expected_arrivals_contractor_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_expected_arrivals_location_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_expected_arrivals_tenant_id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_expected_arrivals_visitor_id");

                    b.HasIndex("TenantId", "ArrivalCode")
                        .IsUnique()
                        .HasDatabaseName("ix_expected_arrivals_tenant_id_arrival_code");

                    b.ToTable("expected_arrivals", "reception");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ArrivalEntry", b =>
                {
                    b.HasOne("Fabric.Server.Reception.Domain.ExpectedArrival", null)
                        .WithMany("Entries")
                        .HasForeignKey("expected_arrival_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arrival_entries_expected_arrivals_expected_arrival_id");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.CheckInDocument", b =>
                {
                    b.HasOne("Fabric.Server.Reception.Domain.ExpectedArrival", null)
                        .WithMany("Documents")
                        .HasForeignKey("expected_arrival_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_in_documents_expected_arrivals_expected_arrival_id");
                });

            modelBuilder.Entity("Fabric.Server.Reception.Domain.ExpectedArrival", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
