using System.Text.Json.Serialization;
using Fabric.Server.Core;
using Fabric.Server.Kiosk.Contracts;
using Fabric.Server.Kiosk.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Fabric.Server.Kiosk;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
[JsonSerializable(typeof(KioskMode))]
[JsonSerializable(typeof(KioskSessionStatus))]
[JsonSerializable(typeof(KioskAssetKind))]
[JsonSerializable(typeof(KioskDeviceType))]
[JsonSerializable(typeof(KioskProfileResponse))]
[JsonSerializable(typeof(CreateKioskProfileRequest))]
[JsonSerializable(typeof(UpdateKioskProfileRequest))]
[JsonSerializable(typeof(KioskResponse))]
[JsonSerializable(typeof(CreateKioskRequest))]
[JsonSerializable(typeof(UpdateKioskRequest))]
[JsonSerializable(typeof(KioskKeyResponse))]
[JsonSerializable(typeof(AssignKioskWorkflowRequest))]
[JsonSerializable(typeof(KioskProfileLanguageResponse))]
[JsonSerializable(typeof(KioskProfileLanguageResponse[]))]
[JsonSerializable(typeof(UpsertKioskProfileLanguagesRequest))]
[JsonSerializable(typeof(KioskTranslationResponse))]
[JsonSerializable(typeof(KioskTranslationResponse[]))]
[JsonSerializable(typeof(UpsertKioskTranslationsRequest))]
[JsonSerializable(typeof(KioskThemeTokenResponse))]
[JsonSerializable(typeof(KioskThemeTokenResponse[]))]
[JsonSerializable(typeof(UpsertKioskThemeRequest))]
[JsonSerializable(typeof(KioskWelcomeSettingsResponse))]
[JsonSerializable(typeof(UpsertKioskWelcomeSettingsRequest))]
[JsonSerializable(typeof(KioskHardwareBindingResponse))]
[JsonSerializable(typeof(KioskHardwareBindingResponse[]))]
[JsonSerializable(typeof(UpsertKioskHardwareBindingsRequest))]
[JsonSerializable(typeof(KioskDeviceAssignmentResponse))]
[JsonSerializable(typeof(KioskDeviceAssignmentResponse[]))]
[JsonSerializable(typeof(UpsertKioskDeviceAssignmentsRequest))]
[JsonSerializable(typeof(KioskDeviceResponse))]
[JsonSerializable(typeof(KioskDeviceResponse[]))]
[JsonSerializable(typeof(UpsertKioskDevicesRequest))]
[JsonSerializable(typeof(KioskAssetResponse))]
[JsonSerializable(typeof(KioskAssetResponse[]))]
[JsonSerializable(typeof(KioskSessionResponse))]
[JsonSerializable(typeof(KioskConfigResponse))]
[JsonSerializable(typeof(ResolvedKioskWelcomeResponse))]
[JsonSerializable(typeof(StartKioskSessionRequest))]
[JsonSerializable(typeof(ChangeKioskLanguageRequest))]
[JsonSerializable(typeof(KioskHeartbeatRequest))]
[JsonSerializable(typeof(KioskInstructionResponse))]
[JsonSerializable(typeof(SubmitKioskInstructionResponseRequest))]
[JsonSerializable(typeof(Domain.KioskInstruction))]
[JsonSerializable(typeof(Domain.KioskMessageInstruction))]
[JsonSerializable(typeof(Domain.KioskChoiceInstruction))]
[JsonSerializable(typeof(Domain.KioskFormInstruction))]
[JsonSerializable(typeof(Domain.KioskChoiceInstructionResult))]
[JsonSerializable(typeof(Domain.KioskFormInstructionResult))]
[JsonSerializable(typeof(Domain.KioskInstructionLayout))]
[JsonSerializable(typeof(Domain.KioskInstructionContent))]
[JsonSerializable(typeof(Domain.KioskChoiceOption))]
[JsonSerializable(typeof(Domain.KioskFormField))]
[JsonSerializable(typeof(Page<KioskProfileResponse>))]
[JsonSerializable(typeof(Page<KioskResponse>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(IFormFile))]
internal sealed partial class KioskJsonSerializerContext : JsonSerializerContext;
