// <auto-generated />
using System;
using Fabric.Server.AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.AccessControl.Persistence.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20260722084835_AddAccessDurationKinds")]
    partial class AddAccessDurationKinds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access_control")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_access_control_systems");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_control_systems_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_access_control_systems_tenant_id_name");

                    b.ToTable("access_control_systems", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystemLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_access_control_system_locations");

                    b.HasIndex("AccessControlSystemId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_control_system_locations_tenant_id");

                    b.HasIndex("TenantId", "AccessControlSystemId")
                        .HasDatabaseName("ix_access_control_system_locations_tenant_id_access_control_system_id");

                    b.HasIndex("TenantId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_control_system_locations_tenant_id_location_id");

                    b.ToTable("access_control_system_locations", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_access_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_items_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_access_items_tenant_id_name");

                    b.ToTable("access_items", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessLevelTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("target_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id")
                        .HasName("pk_access_level_targets");

                    b.HasIndex("AccessControlSystemId");

                    b.HasIndex("AccessItemId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_level_targets_tenant_id");

                    b.HasIndex("TenantId", "AccessControlSystemId")
                        .HasDatabaseName("ix_access_level_targets_tenant_id_access_control_system_id");

                    b.HasIndex("TenantId", "AccessItemId")
                        .HasDatabaseName("ix_access_level_targets_tenant_id_access_item_id");

                    b.ToTable("access_level_targets", "access_control");

                    b.HasDiscriminator<string>("target_type").HasValue("AccessLevelTarget");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.PACSAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<Guid>("AccessLevelTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_level_target_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DurationKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration_kind");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("NativeAssignmentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("native_assignment_id");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provisioned_at");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<Guid>("SourceAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_assignment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_pacs_assignments");

                    b.HasIndex("AccessControlSystemId");

                    b.HasIndex("AccessLevelTargetId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_pacs_assignments_tenant_id");

                    b.HasIndex("TenantId", "AccessControlSystemId", "Status")
                        .HasDatabaseName("ix_pacs_assignments_tenant_id_system_id_status");

                    b.HasIndex("TenantId", "IdentityId", "Status")
                        .HasDatabaseName("ix_pacs_assignments_tenant_id_identity_id_status");

                    b.HasIndex("TenantId", "SourceAssignmentId", "AccessLevelTargetId", "IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_pacs_assignments_tenant_id_source_target_identity");

                    b.ToTable("pacs_assignments", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.PACSSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at");

                    b.Property<string>("NativeSubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("native_subject_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pacs_subjects");

                    b.HasIndex("AccessControlSystemId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_pacs_subjects_tenant_id");

                    b.HasIndex("TenantId", "AccessControlSystemId", "IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_pacs_subjects_tenant_id_system_id_identity_id");

                    b.HasIndex("TenantId", "AccessControlSystemId", "NativeSubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_pacs_subjects_tenant_id_system_id_native_subject_id");

                    b.ToTable("pacs_subjects", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.PACSSubjectProvisioning", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DesiredEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("desired_email");

                    b.Property<string>("DesiredFirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("desired_first_name");

                    b.Property<string>("DesiredLastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("desired_last_name");

                    b.Property<string>("DesiredState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("desired_state");

                    b.Property<string>("LastKnownError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_known_error");

                    b.Property<DateTimeOffset?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<Guid>("PACSSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacs_subject_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pacs_subject_provisionings");

                    b.HasIndex("PACSSubjectId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_pacs_subject_provisionings_tenant_id");

                    b.HasIndex("TenantId", "PACSSubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_pacs_subject_provisionings_tenant_id_pacs_subject_id");

                    b.HasIndex("TenantId", "Status", "ScheduledFor")
                        .HasDatabaseName("ix_pacs_subject_provisionings_tenant_id_status_scheduled_for");

                    b.ToTable("pacs_subject_provisionings", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.UnipassAccessLevelTarget", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessControl.Domain.AccessLevelTarget");

                    b.Property<int>("AccessRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("access_rule_id");

                    b.Property<string>("AccessRuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("access_rule_name");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site_name");

                    b.HasIndex("TenantId", "AccessItemId", "AccessControlSystemId", "SiteId", "AccessRuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_level_targets_tenant_id_item_system_site_rule");

                    b.HasDiscriminator().HasValue("unipass");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystem", b =>
                {
                    b.OwnsOne("Fabric.Server.AccessControl.Domain.UnipassSystemConfig", "UnipassConfig", b1 =>
                        {
                            b1.Property<Guid>("AccessControlSystemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Endpoint")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("unipass_endpoint");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("unipass_password");

                            b1.Property<bool>("SslValidation")
                                .HasColumnType("boolean")
                                .HasColumnName("unipass_ssl_validation");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("unipass_username");

                            b1.HasKey("AccessControlSystemId");

                            b1.ToTable("access_control_systems", "access_control");

                            b1.WithOwner()
                                .HasForeignKey("AccessControlSystemId");
                        });

                    b.Navigation("UnipassConfig");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystemLocation", b =>
                {
                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessControlSystem", null)
                        .WithMany()
                        .HasForeignKey("AccessControlSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_control_system_locations_access_control_systems_access_control_system_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessLevelTarget", b =>
                {
                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessControlSystem", null)
                        .WithMany()
                        .HasForeignKey("AccessControlSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_targets_access_control_systems_access_control_system_id");

                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessItem", null)
                        .WithMany()
                        .HasForeignKey("AccessItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_targets_access_items_access_item_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.PACSAssignment", b =>
                {
                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessControlSystem", null)
                        .WithMany()
                        .HasForeignKey("AccessControlSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pacs_assignments_access_control_systems_access_control_system_id");

                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessLevelTarget", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pacs_assignments_access_level_targets_access_level_target_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.PACSSubject", b =>
                {
                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessControlSystem", null)
                        .WithMany()
                        .HasForeignKey("AccessControlSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pacs_subjects_access_control_systems_access_control_system_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.PACSSubjectProvisioning", b =>
                {
                    b.HasOne("Fabric.Server.AccessControl.Domain.PACSSubject", null)
                        .WithMany()
                        .HasForeignKey("PACSSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pacs_subject_provisionings_pacs_subjects_pacs_subject_id");
                });
#pragma warning restore 612, 618
        }
    }
}
