// <auto-generated />
using System;
using Fabric.Server.AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.AccessControl.Persistence.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20260722065511_AddAccessControlContext")]
    partial class AddAccessControlContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access_control")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_access_control_systems");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_control_systems_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_access_control_systems_tenant_id_name");

                    b.ToTable("access_control_systems", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystemLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_access_control_system_locations");

                    b.HasIndex("AccessControlSystemId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_control_system_locations_tenant_id");

                    b.HasIndex("TenantId", "AccessControlSystemId")
                        .HasDatabaseName("ix_access_control_system_locations_tenant_id_access_control_system_id");

                    b.HasIndex("TenantId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_control_system_locations_tenant_id_location_id");

                    b.ToTable("access_control_system_locations", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_access_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_items_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_access_items_tenant_id_name");

                    b.ToTable("access_items", "access_control");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessLevelTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessControlSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_control_system_id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("target_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id")
                        .HasName("pk_access_level_targets");

                    b.HasIndex("AccessControlSystemId");

                    b.HasIndex("AccessItemId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_level_targets_tenant_id");

                    b.HasIndex("TenantId", "AccessControlSystemId")
                        .HasDatabaseName("ix_access_level_targets_tenant_id_access_control_system_id");

                    b.HasIndex("TenantId", "AccessItemId")
                        .HasDatabaseName("ix_access_level_targets_tenant_id_access_item_id");

                    b.ToTable("access_level_targets", "access_control");

                    b.HasDiscriminator<string>("target_type").HasValue("AccessLevelTarget");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.UnipassAccessLevelTarget", b =>
                {
                    b.HasBaseType("Fabric.Server.AccessControl.Domain.AccessLevelTarget");

                    b.Property<int>("AccessRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("access_rule_id");

                    b.Property<string>("AccessRuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("access_rule_name");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site_name");

                    b.HasIndex("TenantId", "AccessItemId", "AccessControlSystemId", "SiteId", "AccessRuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_level_targets_tenant_id_item_system_site_rule");

                    b.HasDiscriminator().HasValue("unipass");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystem", b =>
                {
                    b.OwnsOne("Fabric.Server.AccessControl.Domain.UnipassSystemConfig", "UnipassConfig", b1 =>
                        {
                            b1.Property<Guid>("AccessControlSystemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Endpoint")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("unipass_endpoint");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("unipass_password");

                            b1.Property<bool>("SslValidation")
                                .HasColumnType("boolean")
                                .HasColumnName("unipass_ssl_validation");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("unipass_username");

                            b1.HasKey("AccessControlSystemId");

                            b1.ToTable("access_control_systems", "access_control");

                            b1.WithOwner()
                                .HasForeignKey("AccessControlSystemId");
                        });

                    b.Navigation("UnipassConfig");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessControlSystemLocation", b =>
                {
                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessControlSystem", null)
                        .WithMany()
                        .HasForeignKey("AccessControlSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_control_system_locations_access_control_systems_access_control_system_id");
                });

            modelBuilder.Entity("Fabric.Server.AccessControl.Domain.AccessLevelTarget", b =>
                {
                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessControlSystem", null)
                        .WithMany()
                        .HasForeignKey("AccessControlSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_targets_access_control_systems_access_control_system_id");

                    b.HasOne("Fabric.Server.AccessControl.Domain.AccessItem", null)
                        .WithMany()
                        .HasForeignKey("AccessItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_targets_access_items_access_item_id");
                });
#pragma warning restore 612, 618
        }
    }
}
