// <auto-generated />
using System;
using Fabric.Server.Employees.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Employees.Persistence.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20260722063304_AddEmployeeLifecycleScheduling")]
    partial class AddEmployeeLifecycleScheduling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("employees")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Employees.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_end_date");

                    b.Property<DateOnly?>("ContractStartDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_start_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirectoryId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("directory_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employee_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_employee_id");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employees_tenant_id");

                    b.HasIndex("TenantId", "DirectoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_tenant_id_directory_id")
                        .HasFilter("directory_id IS NOT NULL");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_employees_tenant_id_email");

                    b.HasIndex("TenantId", "EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_tenant_id_employee_number")
                        .HasFilter("employee_number IS NOT NULL");

                    b.HasIndex("TenantId", "IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_tenant_id_identity_id");

                    b.HasIndex("TenantId", "ManagerEmployeeId")
                        .HasDatabaseName("ix_employees_tenant_id_manager_employee_id");

                    b.HasIndex("TenantId", "OrganizationUnitId")
                        .HasDatabaseName("ix_employees_tenant_id_organization_unit_id");

                    b.ToTable("employees", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLeavePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("Until")
                        .HasColumnType("date")
                        .HasColumnName("until_date");

                    b.HasKey("Id")
                        .HasName("pk_employee_leave_periods");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_leave_periods_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId", "From", "Until")
                        .HasDatabaseName("ix_employee_leave_periods_tenant_id_employee_id_dates");

                    b.ToTable("employee_leave_periods", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_employee_lifecycle_events");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_lifecycle_events_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId", "EffectiveAt")
                        .HasDatabaseName("ix_employee_lifecycle_events_tenant_id_employee_id_effective_at");

                    b.ToTable("employee_lifecycle_events", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLifecycleRecalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_lifecycle_recalculations");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_lifecycle_recalculations_tenant_id");

                    b.HasIndex("TenantId", "Status", "ScheduledFor")
                        .HasDatabaseName("ix_employee_lifecycle_recalculations_tenant_id_status_scheduled_for");

                    b.HasIndex("TenantId", "EmployeeId", "ScheduledFor", "Reason")
                        .HasDatabaseName("ix_employee_lifecycle_recalculations_tenant_id_employee_id_schedule_reason");

                    b.ToTable("employee_lifecycle_recalculations", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLifecycleState", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_status");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<DateTimeOffset>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluated_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employee_lifecycle_states");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_lifecycle_states_tenant_id");

                    b.HasIndex("TenantId", "CurrentStatus")
                        .HasDatabaseName("ix_employee_lifecycle_states_tenant_id_current_status");

                    b.ToTable("employee_lifecycle_states", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeePersona", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("EmployeeId", "PersonaId")
                        .HasName("pk_employee_personas");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_personas_tenant_id");

                    b.HasIndex("TenantId", "PersonaId")
                        .HasDatabaseName("ix_employee_personas_tenant_id_persona_id");

                    b.ToTable("employee_personas", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeSuspensionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("Until")
                        .HasColumnType("date")
                        .HasColumnName("until_date");

                    b.HasKey("Id")
                        .HasName("pk_employee_suspension_periods");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_suspension_periods_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId", "From", "Until")
                        .HasDatabaseName("ix_employee_suspension_periods_tenant_id_employee_id_dates");

                    b.ToTable("employee_suspension_periods", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeWorkLocation", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("EmployeeId", "LocationId")
                        .HasName("pk_employee_work_locations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_work_locations_tenant_id");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_employee_work_locations_tenant_id_location_id");

                    b.ToTable("employee_work_locations", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organization_units");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_organization_units_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_units_tenant_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_organization_units_tenant_id_is_active");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_organization_units_tenant_id_name");

                    b.HasIndex("TenantId", "ParentId")
                        .HasDatabaseName("ix_organization_units_tenant_id_parent_id");

                    b.ToTable("organization_units", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnitClosure", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_id");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("AncestorId", "DescendantId")
                        .HasName("pk_organization_unit_closures");

                    b.HasIndex("DescendantId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_organization_unit_closures_tenant_id");

                    b.HasIndex("TenantId", "AncestorId", "Depth")
                        .HasDatabaseName("ix_org_unit_closures_tenant_id_ancestor_id_depth");

                    b.HasIndex("TenantId", "DescendantId", "Depth")
                        .HasDatabaseName("ix_org_unit_closures_tenant_id_descendant_id_depth");

                    b.ToTable("organization_unit_closures", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_personas");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_personas_tenant_id");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_personas_tenant_id_is_active");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_personas_tenant_id_name");

                    b.ToTable("personas", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.Employee", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLeavePeriod", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany("LeavePeriods")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLifecycleEvent", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLifecycleRecalculation", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeLifecycleState", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeePersona", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany("Personas")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fabric.Server.Employees.Domain.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeSuspensionPeriod", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany("SuspensionPeriods")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.EmployeeWorkLocation", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany("WorkLocations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnit", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnitClosure", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.Employee", b =>
                {
                    b.Navigation("LeavePeriods");

                    b.Navigation("Personas");

                    b.Navigation("SuspensionPeriods");

                    b.Navigation("WorkLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
