// <auto-generated />
using System;
using Fabric.Server.Employees.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Employees.Persistence.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    partial class EmployeesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("employees")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Employees.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employee_number");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<DateTimeOffset?>("LeaveStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leave_started_at");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_employee_id");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("termination_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employees_tenant_id");

                    b.HasIndex("TenantId", "EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_tenant_id_employee_number")
                        .HasFilter("employee_number IS NOT NULL");

                    b.HasIndex("TenantId", "IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_tenant_id_identity_id");

                    b.HasIndex("TenantId", "ManagerEmployeeId")
                        .HasDatabaseName("ix_employees_tenant_id_manager_employee_id");

                    b.HasIndex("TenantId", "OrganizationUnitId")
                        .HasDatabaseName("ix_employees_tenant_id_organization_unit_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_employees_tenant_id_status");

                    b.ToTable("employees", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organization_units");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_organization_units_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_units_tenant_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_organization_units_tenant_id_is_active");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_organization_units_tenant_id_name");

                    b.HasIndex("TenantId", "ParentId")
                        .HasDatabaseName("ix_organization_units_tenant_id_parent_id");

                    b.ToTable("organization_units", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnitClosure", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_id");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("AncestorId", "DescendantId")
                        .HasName("pk_organization_unit_closures");

                    b.HasIndex("DescendantId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_organization_unit_closures_tenant_id");

                    b.HasIndex("TenantId", "AncestorId", "Depth")
                        .HasDatabaseName("ix_org_unit_closures_tenant_id_ancestor_id_depth");

                    b.HasIndex("TenantId", "DescendantId", "Depth")
                        .HasDatabaseName("ix_org_unit_closures_tenant_id_descendant_id_depth");

                    b.ToTable("organization_unit_closures", "employees");
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.Employee", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnit", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fabric.Server.Employees.Domain.OrganizationUnitClosure", b =>
                {
                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fabric.Server.Employees.Domain.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
